### PR TITLE
Adding elm talk

### PR DESCRIPTION
**Pull request by JordyMoos**
Hello,

I hope you will accept my talk about Elm!
A link to the slides and my speaking history are in the PR.

Cheers!

### CODE REVIEW

**Review by stefanomasini — COMMENTED** [review]
Hi Jordy. We noticed you added your proposal for 2017-09 (i.e. september). Just to be clear: we're not planning on hosting a meetup in September. The next meetup will be in Aug 28. For that meetup we already have a pending proposal for a long talk. We're open to considering a second one, but we're not sure whether we want to have 2 long ones. Otherwise, the meetup after that will be in October. And, of course, for us it would be nice to have you just as much. Let us know what date/format you prefer.

**Comment by JordyMoos** [comment]
Hi Stefano. Ok no problem, i moved the proposal to October.

**Comment by JordyMoos** [comment]
The slides with code screenshots are actually not in the official slides. Then those will be live coded and thereby explained etc

**Review by pietvanzoen — APPROVED** [review]
Sorry for the delay Jordy! This looks great, looking forward to it!

Be sure to say hi at the August meetup if you're coming along.

**Pull request merged**
